In [1]:
import numpy as np

# Estrutuda de Dados Numpy

In [2]:
# Array Unidimensional
array1 = np.array([10,20,30,40])

In [3]:
# Array Bi-dimensional
array2 = np.array([[100,83,15], [42,78,0]])

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [6]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [7]:
array2.shape

(2, 3)

In [8]:
# Verificando o número de dimensões
array2.ndim

2

In [9]:
# Método
array2.max()

100

In [10]:
# Atributo
array2.ndim

2

# Criando estruturas de dados com arange

In [11]:
array3 = np.arange(15)

In [12]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Utilizando start/end (exclusivo)
array4 = np.arange(0,15,5)

In [14]:
array4

array([ 0,  5, 10])

# Criando estruturas de dados com linspace

In [16]:
# Argumentos (start, end, numero de elementos)
array5 = np.linspace(0, 3, 4)

In [17]:
array5

array([0., 1., 2., 3.])

# Criando estruturas de dados com outras funções

In [18]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8))

In [19]:
array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# Array 2x3x2 de 1
array7 = np.ones((2, 3, 2))

In [21]:
array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
# Matriz diagonal 1
array8 = np.eye(3)

In [23]:
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Matriz diagonal passando o valor da diagonal
array9 = np.diag((2, 1, 4, 6))

In [26]:
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])