In [1]:
import numpy as np

# Estrutuda de Dados Numpy

In [2]:
# Array Unidimensional
array1 = np.array([10,20,30,40])

In [3]:
# Array Bi-dimensional
array2 = np.array([[100,83,15], [42,78,0]])

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [6]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [7]:
array2.shape

(2, 3)

In [8]:
# Verificando o número de dimensões
array2.ndim

2

In [9]:
# Método
array2.max()

100

In [10]:
# Atributo
array2.ndim

2

# Criando estruturas de dados com arange

In [11]:
array3 = np.arange(15)

In [12]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Utilizando start/end (exclusivo)
array4 = np.arange(0,15,5)

In [14]:
array4

array([ 0,  5, 10])

# Criando estruturas de dados com linspace

In [15]:
# Argumentos (start, end, numero de elementos)
array5 = np.linspace(0, 3, 4)

In [16]:
array5

array([0., 1., 2., 3.])

# Criando estruturas de dados com outras funções

In [17]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8))

In [18]:
array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# Array 2x3x2 de 1
array7 = np.ones((2, 3, 2))

In [20]:
array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
# Matriz diagonal 1
array8 = np.eye(3)

In [22]:
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Matriz diagonal passando o valor da diagonal
array9 = np.diag((2, 1, 4, 6))

In [24]:
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [25]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100)
array10 = np.random.rand(5)
array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [26]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5)
array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [27]:
array12 = np.empty((3,2))
array12

array([[ 1.72723371e-077, -2.68678694e+154],
       [ 1.48219694e-323,  0.00000000e+000],
       [ 0.00000000e+000,  4.17201348e-309]])

In [28]:
np.array([[9,4], [3,7]])

array([[9, 4],
       [3, 7]])

In [29]:
# Duplicar, Ladrilhar
np.tile(np.array([[9,4], [3,7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [30]:
np.tile(np.array([[9,4], [3,7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de Dados Numpy

In [31]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [32]:
array13

array([ 8., -3.,  5.,  9.])

In [33]:
array13.dtype

dtype('float64')

In [34]:
array14 = np.array([2, 4, 6, 8])

In [35]:
array14

array([2, 4, 6, 8])

In [36]:
array14.dtype

dtype('int64')

In [37]:
array15 = np.array([2.0, 4, 6, 8])

In [38]:
array15

array([2., 4., 6., 8.])

In [39]:
array15.dtype

dtype('float64')

In [40]:
array16 = np.array(['Análise', 'de', 'Dados', 'com Python'])

In [41]:
array16.dtype

dtype('<U10')

In [42]:
array17 = np.array([True, False, True])

In [43]:
array17.dtype

dtype('bool')

In [44]:
array18 = np.array([7, -3, 5.24])

In [45]:
array18.dtype

dtype('float64')

In [46]:
array18.astype(int)

array([ 7, -3,  5])

## Operações com Arrays

In [47]:
# Array começando por 0, com 30 elementos e multiplicado por 5
array19 = np.arange(0, 30) * 5

In [48]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [49]:
array19 = np.arange(0, 30)

In [50]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
# Elevando um array a portência
array20 = np.arange(5) ** 4

In [52]:
array20

array([  0,   1,  16,  81, 256])

In [53]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [54]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
array22 = np.arange(0, 30, 3) + 3
array23 = np.arange(1, 11)

In [56]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [57]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [60]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [61]:
# Multiplicacao
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [62]:
# Comparação de arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [63]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

## Comparação de Array: Python x NumPy

In [64]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

2.87 µs ± 14.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

289 µs ± 1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
